### ISSUE TITLE
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign

### ISSUE THREAD

**Issue by shadycuz** [linuxserver/docker-plex#110]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

I'm running this on kubernetes, might be the issue.

Settings for my deployment.
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: linuxserver/plex
        env:
        - name: VERSION
          value: latest
        - name: TZ
          value: America/New_York
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data/tvshows
          name: media
        - mountPath: /data/movies
          name: media
        ports:
        - containerPort: 32400
          protocol: UDP
        - containerPort: 32400
          protocol: TCP
        - containerPort: 32469
          protocol: TCP
        - containerPort: 32469
          protocol: UDP
        - containerPort: 5353
          protocol: UDP
        - containerPort: 1900
          protocol: UDP
      volumes:
      - name: config
        emptyDir: {}
      - name: media
        hostPath:
          path: /home/plex/media
```

Container logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
usermod: no changes
 -------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|
 Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------
 [cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-dbus: executing... 
[cont-init.d] 30-dbus: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-plex-update: executing... 
 #####################################################
#   Login via the webui at http://<ip>:32400/web    #
#   and restart the docker, because there was no    #
#   preference file found, possibly first startup.  #
#####################################################
[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting dbus-daemon
Starting Plex Media Server.
[services.d] done.
Starting Avahi daemon
Found user 'avahi' (UID 106) and group 'avahi' (GID 107).
Successfully dropped root privileges.
avahi-daemon 0.6.32-rc starting up.
No service file found in /etc/avahi/services.
Joining mDNS multicast group on interface eth0.IPv6 with address fe80::fc13:ecff:fe81:fc51.
New relevant interface eth0.IPv6 for mDNS.
Joining mDNS multicast group on interface eth0.IPv4 with address 10.233.125.132.
New relevant interface eth0.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::fc13:ecff:fe81:fc51 on eth0.*.
Registering new address record for 10.233.125.132 on eth0.IPv4.
Server startup complete. Host name is plex-2665985448-cpgg5.local. Local service cookie is 1388827063.
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required):
  --directory arg       Directory to scan for crash reports
  --serverUuid arg      UUID of the server that crashed
  --userId arg          User that owns this product
  --platform arg        Platform string
  --url arg             URL to upload to
  --help                show help message
  --version arg         Version of the product
```

I'm using fuse for my media mounts and they are working fine.

**Comment by shadycuz** [comment]
So this actually works, but once I login I dont see my server. I have even tunneled in like I have to do with all my other VPS plex servers.

**Comment by shadycuz** [comment]
Manage to get the server added =), but I'm getting "Not available outside your network" I know its because of the NAT gateway I'm behind. I'm thinking I need to port forward from the nat gateway back into my cluster.

**Comment by shadycuz** [comment]
The error is still in the log and thats why I opened this issue, but plex is working fine for me on kubernetes. Im just having an issue now with port-forwarding through a VPN setup but I will seek help on StackExchange.

**Comment by thisarattr** [comment]
how did u manage to solve it? Im facing same kind of issue on a rpi. It cannot find any servers, but I can login into account. Any ideas?

**Comment by norwegianwod** [comment]
@shadycuz , I'm facing the same issue. It cannot find any server when I logged into my account via web GUI. Could you share how you fix it please?

**Comment by chb0github** [comment]
Identical issue. The docker file might need updating

**Comment by dasjestyr** [comment]
Ditto. Exact same issue, and I cannot access the web ui

**Comment by yonatanp** [comment]
Nothing beats seeing your problem solved by someone but not knowing how. I <3 Internet!
Also: https://xkcd.com/979/
(same problem for me, @shadycuz if you still remember anything, drop us all a line)

**Comment by yonatanp** [comment]
So - at least my specific problem I've been able to solve. I needed to unregister the server from the plex account, set it up a bit (next next next and pick a new name), and then claim it back to my plex account.
The trick was that the server was remote but in order to sign-in without my plex account, I needed to tunnel the remote port to localhost.
I ran something like: `ssh -f -N -L 10000:localhost:32400 user@10.0.0.123` and then I could access the server at `http://localhost:32400/web`. When I access like this, there's a tiny "what's this?" link at the bottom right when requested to sign in to plex account; and then on the bottom you can "skip it". From there it was easy.

**Comment by shadycuz** [comment]
@thisarattr @norwegianwod @chb0github @dasjestyr @yonatanp 

Heys guys, Sorry I didn't get back with you. I ran this setup on a kubernetes for a month or 2. By the time everyone asked for help I didn't have it set up and couldn't remember how I did it. 

@yonatanp is right, you have to tunnel into the server and access it from 127.0.0.1/localhost in order to "claim it". If you don't you will be able to log into the server but only see other plex servers you already have, not the new one you wish to claim. 

Good instructions can be found here https://forums.plex.tv/discussion/294843/unable-to-claim-server

**Comment by charliestrawn** [comment]
You can also hit up https://www.plex.tv/claim/, sign in, and set that value as `PLEX_CLAIM` environment variable.

**Comment by baptisteArnaud** [comment]
This doesn't work with `PLEX_CLAIM` env...

Here are my logs :
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-gid-video: executing...
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing...
Docker is used for verisoning skip update check
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required):
  --directory arg       Directory to scan for crash reports
  --serverUuid arg      UUID of the server that crashed
  --userId arg          User that owns this product
  --platform arg        Platform string
  --platformVersion arg Platform version string
  --vendor arg          Vendor string
  --device arg          Device string
  --model arg           Device model string
  --sentryUrl arg       Sentry URL to upload to
  --sentryKey arg       Sentry Key for the project
  --version arg         Version of the product
```

I can hit up the plex Web UI but no server found. I run it on my local Kubernetes cluster with a reverse proxy. I'm not sure to understand @yonatanp procedure...

**Comment by aptalca** [comment]
You need to be connecting from the same subnet to set up Plex server. You can try the ssh tunnel method that's described on the Plex website. Google Plex setup ssh tunel

**Comment by baptisteArnaud** [comment]
I succeed in accessing the server from the web UI from my PC. But now I need to access to server from my Android TV box. It fails...

**Comment by Gerthum** [comment]
Just in case anyone comes across this post still having the problem. 

I'm running it on Kubernetes (K3s) and to get my server detected. I ran kubectl port-forward <pod-name> 32400

You can then access the Web Interface on localhost:32400 and it automatically guided me to complete the server setup.

**Comment by leewc** [comment]
^Same issue applies if you're trying to setup Plex with Traefik, just needing to expose a port 32400 to be accessible was all that's needed!

**Comment by enzanto** [comment]
Late to the party. But when i ran the kubctl port-forward i could not claim the server. In the logs it said that it could not resolve plex.tv.

after i added the following to the config it worked

```
dnsConfig:
        options:
          - name: ndots
            value: "1"
```
standard value is 5. so it will not do a proper dns search unless there are 5 dots in address. swapping it to one works like a charm

k3s v1.29
