### ISSUE TITLE
docker hangs when attempting to upgrade plex version

### ISSUE THREAD

**Issue by dbcesar** [linuxserver/docker-plex#131]
Hi,

I'm running docker on Linux Mint 18.2 Sonya. I have a docker-compose to run my plex server and it always have worked fine, but not these last week. The issue is that the docker hangs on the message:
`Atempting to upgrade to: 1.13.5.5291-6fa5e50a8`

These are the last lines after running `docker-compose up`

```
plex    | [cont-init.d] 10-adduser: exited 0.
plex    | [cont-init.d] 30-dbus: executing... 
plex    | [cont-init.d] 30-dbus: exited 0.
plex    | [cont-init.d] 40-chown-files: executing... 
plex    | [cont-init.d] 40-chown-files: exited 0.
plex    | [cont-init.d] 50-plex-update: executing... 
plex    | Atempting to upgrade to: 1.13.5.5291-6fa5e50a8
```

And that is my docker file:

```
version: '2'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/diego/plex-config:/config
      - /home/diego/tv:/tv
      - /home/diego/movies:/movies
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - VERSION=latest
```
Am I missing anything? Thanks
