### ISSUE TITLE
Taking ~5 minutes to load - "Change in ownership detected"

### ISSUE THREAD

**Issue by Jleagle** [linuxserver/docker-plex#139]
Hi, i have Plex running on Debian and while working fine, takes a long time to load up, which is bad for me as I turn my media pc off/on when not using it.

Logs:
```
| Brought to you by linuxserver.io
| We gratefully accept donations at:
| https://www.linuxserver.io/donate/
| -------------------------------------
| GID/UID
| -------------------------------------
|
| User uid:    1000
| User gid:    1000
| -------------------------------------
|
| [cont-init.d] 10-adduser: exited 0.
| [cont-init.d] 30-dbus: executing...
| [cont-init.d] 30-dbus: exited 0.
| [cont-init.d] 40-chown-files: executing...
| Change in ownership detected, please be patient while we chown existing files
| This could take some time
```
After this everything loads instantly.

I am using docker-compose to run Plex using this service:
```
  plex:
    image: linuxserver/plex:latest
    hostname: plex
    container_name: plex
    network_mode: "host"
    restart: "unless-stopped"
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London
    - VERSION=latest
    volumes:
    - ${DOCKER_DATA}/Plex/Transcoding:/transcode
    - /mnt/34D26DEED26DB4B0/Docker/Plex/Config:/config
    - /mnt/34D26DEED26DB4B0/Television:/data/tvshows
    - /mnt/34D26DEED26DB4B0/Video:/data/movies
```
I'm guessing this isn't normal, any ideas what i'm doing wrong? Thanks.

**Comment by j0nnymoe** [comment]
It's because the docker container is changing the ownership of your /config mount back to what they should be. Something on your system is changing them.

**Comment by Jleagle** [comment]
I don't have anything that changes the ownership. Can I change the owner to something on the host machine and it will be fixed in the container?

**Comment by aptalca** [comment]
owner will be set to the id you set in PUID

**Comment by aptalca** [comment]
It should be correct, but either something else on your system is changing the owner on the `Library` folder, or the chown is not successful.

Check the permissions on the host `Library` folder and see if it's owned by jleagle

**Comment by Jleagle** [comment]
In the end this was because the drive with my plex data, was formatted to NTFS & using Fuse. So it wasn't aware of user IDs at all. Thanks.

**Comment by lkjimy** [comment]
For anyone looking for another solution if you are mounting the volume to the container from the windows filesystem...
I had to:
1. Create a docker volume with `docker volume create plex_data`
2. Copy the `Library` directory to the root of the newly created volume
```powershell
docker run --rm -v plex_data:/destination -v "$(pwd):/source" alpine cp -R /source/config/Library /destination/
```
3. Add the volume to the container in the docker-compose file
```yml
# plex service...
  volumes:
        - plex_data:/config

volumes:
  plex_data:
    external: true  
```
4. Start the service `docker compose up -d`
