### ISSUE TITLE
error after start

### ISSUE THREAD

**Issue by D1abloRUS** [linuxserver/docker-plex#144]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

`Ubuntu 18.04`

```
plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    environment:
      VERSION: latest
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
    volumes:
      - /mnt/md0/plex:/config
      - /mnt/md0/data/share/films:/data/movies
      - /mnt/md0/data/share/serials:/data/serials
      - /mnt/md0/data/share/music:/data/music
    network_mode: "host"
```

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-dbus: executing... 
[cont-init.d] 30-dbus: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-plex-update: executing... 



#####################################################
#   Login via the webui at http://<ip>:32400/web    #
#   and restart the docker, because there was no    #
#   preference file found, possibly first startup.  #
#####################################################


[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting dbus-daemon
Starting Plex Media Server.
[services.d] done.
Starting Avahi daemon
Found user 'avahi' (UID 102) and group 'avahi' (GID 103).
Successfully dropped root privileges.
avahi-daemon 0.7 starting up.
No service file found in /etc/avahi/services.
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
New relevant interface docker0.IPv4 for mDNS.
New relevant interface enp37s0.IPv6 for mDNS.
Joining mDNS multicast group on interface enp37s0.IPv4 with address 192.168.245.52.
New relevant interface enp37s0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv6 with address ::1.
New relevant interface lo.IPv6 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for 192.168.245.52 on enp37s0.IPv4.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
Server startup complete. Host name is nas.local. Local service cookie is 2354985576.
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required):
  --directory arg       Directory to scan for crash reports
  --serverUuid arg      UUID of the server that crashed
  --userId arg          User that owns this product
  --platform arg        Platform string
  --url arg             URL to upload to
  --help                show help message
  --version arg         Version of the product
```

##  Thanks, team linuxserver.io

I get error after start container, see ^
