### ISSUE TITLE
Unable to connect to the container

### ISSUE THREAD

**Issue by SethGower** [linuxserver/docker-plex#165]
I am trying to create a docker container for plex on my proxmox install, but I can't get it to work. I have tried both the `docker create` and `docker-compose` methods. I am able to create the container and run it, but there is no network connectivity. `iptables` reports that none of the plex ports are in use when I use the `--net=host` method, but when I use the individual ports, I can't connect to them, and when I use `nmap` on another machine, it says that the 32400 port is closed, and I can't connect via the browser. 

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

<!--- If you have an issue with the project, please provide us with the following information -->

Output of `uname -a`: `Linux destiny 4.15.18-9-pve #1 SMP PVE 4.15.18-30 (Thu, 15 Nov 2018 13:32:46 +0100) x86_64 GNU/Linux`

Command using `--net=host`:
```shell
seth@destiny:~% docker create \               
--name=plex \
--net=host \
--restart=always \
-e VERSION=latest \
-e PUID=1000 -e PGID=1001 \
-e TZ=America/New_York \
-v /etc/Plex:/config \
-v /mnt/mass_media/Plex/TV_Shows:/data/tv \
-v /mnt/mass_media/Plex/Movies:/data/movies \
-v /mnt/mass_media/Plex/Music:/data/music \
-v /mnt/mass_media/Plex/Transcode:/transcode \
linuxserver/plex
```

Command using individual ports:
```shell
seth@destiny:~% docker create \               
  --name=plex \
  -p 32400:32400 \
  -p 32400:32400/udp \
  -p 32469:32469 \ 
  -p 32469:32469/udp \     
  -p 5353:5353/udp \    
  -p 1900:1900/udp\   
  -e PUID=1000 \                           
  -e PGID=1000 \                             
  -e VERSION=docker \                      
  -v /etc/Plex:/config \                      
  -v /mnt/mass_media/Plex/TV_Shows:/data/tvshows \
  -v /mnt/mass_media/Plex/Movies:/data/movies \
  -v /mnt/mass_media/Plex/Transcode:/transcode \
  --restart unless-stopped \
  linuxserver/plex
```

Contents of `docker-compose.yml`:
```yaml
---
version: "2"
services:
        plex:
                image: linuxserver/plex
                container_name: plex
                network_mode: host
                environment:
                        - PUID=1000
                        - PGID=1000
                        - VERSION=docker
                volumes:
                        - /etc/Plex:/config
                        - /mnt/mass_media/Plex/TV_Shows:/data/tvshows
                        - /mnt/mass_media/Plex/Movies:/data/movies
                        - /mnt/mass_media/Plex/Music:/data/music
                        - /mnt/mass_media/Plex/Transcode:/transcode
                restart: unless-stopped
```
Output of `docker logs plex`
```
seth@destiny:~% docker logs plex                                                                       
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.                          
[s6-init] ensuring user provided files have correct perms...exited 0.                                  
[fix-attrs.d] applying ownership & permissions fixes...                                                
[fix-attrs.d] done.                                                                                    
[cont-init.d] executing container initialization scripts...                                            
[cont-init.d] 10-adduser: executing...                                          
                                                                                   
-------------------------------------                                                    
          _         ()                                                                              
         | |  ___   _    __                                           
         | | / __| | |  /  \                                                               
         | | \__ \ | | | () |                                                
         |_| |___/ |_|  \__/                                                          
                                                                                      
                                                                                 
Brought to you by linuxserver.io                                   
We gratefully accept donations at:                                                                     
https://www.linuxserver.io/donate/                                        
-------------------------------------                                      
GID/UID                                                                              
-------------------------------------                                      
                                                                                           
User uid:    1000                                                          
User gid:    1001                                                         
-------------------------------------                                     
                                                                                                    
[cont-init.d] 10-adduser: exited 0.                                                                 
[cont-init.d] 40-chown-files: executing...                                                            
[cont-init.d] 40-chown-files: exited 0.                                                             
[cont-init.d] 50-gid-video: executing...                             
[cont-init.d] 50-gid-video: exited 0.                                              
[cont-init.d] 60-plex-update: executing...                            
No update required                                                                                    
[cont-init.d] 60-plex-update: exited 0.                                
[cont-init.d] done.                                                                   
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
```
The `Starting Plex Media Server.` continutes 1600 times. 

I have tried asking this on reddit, and asking a friend who has it working, but neither helped. Any suggestions would help
