### ISSUE TITLE
latest plex 1.16.2.1297-4b7ace214 fails HW acceleration

### ISSUE THREAD

**Issue by crlshn** [linuxserver/docker-plex#192]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 
**Host OS**
ubunutu 16.04.02 LTS
Docker version 18.09.5, build e8ff056
docker-compose version 1.24.0-rc1, build 0f3d4dda

**docker/plex# docker-compose config**
```
services:
  plex:
    devices:
    - /dev/dri:/dev/dri
    environment:
      GUID: '0'
      PLEX_CLAIM: '"xxxxxxxxxxxxxx"'
      PUID: '0'
      TZ: America/Tegucigalpa
      VERSION: latest
    image: plexinc/pms-docker:plexpass
    network_mode: host
    restart: always
    volumes:
    - /home/docker/plex/config:/config:rw
    - /home/docker/plex/transcode:/transcode:rw
    - /dev/shm:/ram_transcode:rw
    - nfs_tv:/data/tv:rw
    - nfs_movies:/data/movies:rw
```

**docker/plex# docker-compose logs -f plex**
```
....
plex_1      | Starting Plex Media Server.
plex_1      | failed to open /data/jenkins/conan_build/289871709/conan/.conan/data/libva/2.1.0-41/plex/stable/package/81a2df5e16044d97d1b088b0e6c9598b5b17f233/lib/dri/hybrid_drv_video.so
plex_1      | Failed to wrapper hybrid_drv_video.so
plex_1      | failed to open /data/jenkins/conan_build/289871709/conan/.conan/data/libva/2.1.0-41/plex/stable/package/81a2df5e16044d97d1b088b0e6c9598b5b17f233/lib/dri/hybrid_drv_video.so
plex_1      | Failed to wrapper hybrid_drv_video.so
plex_1      | failed to open /data/jenkins/conan_build/289871709/conan/.conan/data/libva/2.1.0-41/plex/stable/package/81a2df5e16044d97d1b088b0e6c9598b5b17f233/lib/dri/hybrid_drv_video.so
plex_1      | Failed to wrapper hybrid_drv_video.so
plex_1      | [cont-finish.d] executing container finish scripts...

...
```

NFS mounts in docker (working flawless on the previus plex and not the issue)

I try both images:

 `image: plexinc/pms-docker:plexpass # change this to plexinc/pms-docker:plexpass if you are a plexpass subscriber`

  and 

   `image: linuxserver/plex:latest`

browsing is flawless but I have to remove
 ```
   #devices:
    #  - /dev/dri:/dev/dri

```
to continue to allow playback
not a issue of linuxserver template, maybe is an issue inside plex program itself

in my case the Intel NUC i3 needs HW acceleration to be able to playback 4k/1080p hopefully HW return soon
