### ISSUE TITLE
You don't have any media servers yet.

### ISSUE THREAD

**Issue by b0red** [linuxserver/docker-plex#201]
Doing a new install of my ubuntuserver (v19.04) and I get this message when trying to install plex media server_You

**You don't have any media servers yet.
Download and install one and try again.**

I've reinstalled this docker container multiple times, purgin the containers between installs, but I keep getting the same error as above. I've tried in Chrome, IE, Opera.
What to do to get this working?

Short background:
server crashed, did a reinstall and updated to ubuntu 19.04 from 18.04, installed docker and compose, docker is working since I'm running others linuxserver containers, like Sickchill and things like that.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu Disco Dingo  19.04

running the linuxserver template (same as before install, everything was working fine)

```
 plex:
    image: "linuxserver/plex:latest"
    #image: "plexinc/pms-docker:latest"
    container_name: "plexms"
    restart: always
    volumes:
      - ${USERDIR}/docker/plex/config:/config
      - ${USERDIR}/docker/shared:/shared
      - ${USERDIR}/docker/plex/plextemp:/transcode:rw
      - ${USERDIR}/docker/backups:/backups
      - ${USERDIR}/docker/letsencrypt/config/etc/letsencrypt:/le-ssl
      - /media/Movies:/media/film
      - /media/tv1:/media/tv1
      - /media/tv2:/media/tv2
      - /media/Music:/media/music
    ports:
      - "32400:32400"
      - "33400:33400/udp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    networks:
      - default
      - traefik_proxy
    environment:
      - NET=host
      - HOSTNAME="Docker plex"
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - VERSION=docker
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
      - PLEX_CLAIM=${PLEX_CLAIM}
```

```
<code>
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    911,
User gid:    911,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 40-chown-files: executing... ,
[cont-init.d] 40-chown-files: exited 0.,
[cont-init.d] 50-gid-video: executing... ,
[cont-init.d] 50-gid-video: exited 0.,
[cont-init.d] 60-plex-update: executing... ,
Docker is used for verisoning skip update check,
[cont-init.d] 60-plex-update: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
Starting Plex Media Server.,
[services.d] done.,
</code>
```

Links to my synology NAS in the linux file system
