### ISSUE TITLE
Environment vars from environment section of docker-compose are not set in container

### ISSUE THREAD

**Issue by udochrist** [linuxserver/docker-plex#203]
Hi

 i am using docker on Synology (x64) and have recently updated the docker package to the latest syno version. docker-compose shows version
```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
```

my plex server docker-compose.yml is
```
version: '2'
services:

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    hostname: 'name.internal'
    network_mode: host
    environment:
      - PUID=1027
      - PGID=65537
      - VERSION=latest
    volumes:
....

```

after a ```docker-compose pull && docker-compose up -d``` my container is messed up.
The PUID and PGID are not set on the container Env variables hosing up my config permissions in the container /config directory. It seems that none of the Env vars from "environment" are set. The container is using the 911 / 911 ids which seem to be the default if no env vars are set for the two values.

this has been working like a charm for 2 years and now with the update of the image as well as the docker software packge all hell broke loose.
I have no idea what is going on and/or how to fix this, but the issue is reproducible with other containers as well. As soon as a i "pull" and then "up -d" the variables get lost on the container.
