### ISSUE TITLE
Incorrect permissions for /dev/dri

### ISSUE THREAD

**Issue by kevindd992002** [linuxserver/docker-plex#207]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

##  Thanks, team linuxserver.io

In your docuemntation, it says:

> Hardware acceleration users for Intel Quicksync will need to mount their /dev/dri video device inside of the container by passing the following command when running or creating the container:
> 
> --device=/dev/dri:/dev/dri
> 
> We will automatically ensure the abc user inside of the container has the proper permissions to access this device.

I'm running docker-compose with Debian 10/Linux Kernel 5.2 (Buster Backports). I have my docker-compose.yml file set like so:

```
 plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    volumes:
      - /home/kevin/appdata/plex:/config
      - /mnt/storage/shows:/data/tvshows
      - /mnt/storage/movies:/data/movies
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Manila
      - VERSION=latest
```

Output of `ls -la /dev/dri` in my host machine is:

```
root@epsilon:~# ls -la /dev/dri
total 0
drwxr-xr-x  3 root root        100 Sep 16 00:04 .
drwxr-xr-x 17 root root       3520 Sep 16 00:04 ..
drwxr-xr-x  2 root root         80 Sep 16 00:04 by-path
crw-rw----  1 root video  226,   0 Sep 16 00:04 card0
crw-rw----  1 root render 226, 128 Sep 16 00:04 renderD128
```

Output of `ls -la /dev/dri` inside the plex container is:

```
root@epsilon:/# ls -la /dev/dri
total 0
drwxr-xr-x 2 root root        80 Sep 16 00:04 .
drwxr-xr-x 6 root root       360 Sep 16 00:04 ..
crw-rw---- 1 root video 226,   0 Sep 16 00:04 card0
crw-rw---- 1 root   105 226, 128 Sep 16 00:04 renderD128
```

This clearly is an issue because the container does not have the `render` group which means that the abc user does not have access to the `renderD128` device. This breaks HW transcoding. As a workaround, I can `chown` renderD128 so that it is owned by the PUID I specified. This is not an ideal solution because upon restart the permissions of those devices get reset and we shouldn't do this extra step anyway if the container is working correctly. Changing device permissions is not good practice at all.

@aptalca is already aware of this issue as I mentioned it in the Discord channel. I hope you guys can take a look at this and acknowledge it as a real issue. Thank you very much for your continued support and great work for the community!
