### ISSUE TITLE
Plex not detecting previous server

### ISSUE THREAD

**Issue by raphattack** [linuxserver/docker-plex#209]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

The previous server should be detected after migrating over backup.

## Current Behavior

The previous server is not detected. A nearby server with the same name is detected, but does not have existing libraries, so everything needs to be added again.

## Steps to Reproduce

1. Copy backup files from existing Plex.
```bash
sudo cp -r /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/* config/
```
2. Run `docker-compose up -d`
3. Browse to http://192.168.1.3:32400/web
4. Duplicate nearby server is found with empty libraries. Existing server is unreachable. 
**Note:** Movies library is showing because I manually added it.
<img width="192" alt="Screen Shot 2019-10-11 at 6 29 15 PM" src="https://user-images.githubusercontent.com/1328300/66692792-af114d00-ec56-11e9-88a4-9315ea0053d5.png">

## Environment
**OS:** Ubuntu 18.04
**CPU architecture:** x86_64
**How docker service was installed:** installed via [official guide](https://docs.docker.com/compose/install/).

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up -d`

```yaml
docker-compose.yml

version: "2"
 services:
   plex:
     image: linuxserver/plex
     container_name: plex
     network_mode: host
     environment:
       - PUID=1000
       - PGID=995
       - VERSION=docker
     volumes:
       - ./config:/config
       - /media/Movies:/media/Movies
       - /media/Shows:/media/Shows
     restart: unless-stopped
```

## Docker logs

```bash
$ docker logs plex
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    995
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-gid-video: executing...
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing...
Docker is used for verisoning skip update check
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
Exception AttributeError: "'ZipArchive' object has no attribute '_zip'" in <bound method ZipArchive.__del__ of <Framework.components.data.ZipArchive object at 0x7ff96cde3390>> ignored
```
