### ISSUE TITLE
[Issue] iHD_drv_video.so is not working with Intel Gemini Lake

### ISSUE THREAD

**Issue by Jqh63** [linuxserver/docker-plex#228]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## iHD_drv_video.so issue with Intel Gemini Lake
Had to remove iHD_drv_video.so into every LSIO fresh image (Ubuntu default intel GPU driver issue?) to get plex HW transcode working.
FYI, many threads on plex forum mention this issue and one specific [plex forum very old issue](https://forums.plex.tv/t/corrupted-video-output-stream-with-hardware-transcoding/500432/85)
Plus, nothing revelant found on Intel side [intel driver git](https://github.com/intel/media-driver/issues/), maybe [encode issue](https://github.com/intel/media-driver/issues/733)

## Expected Behavior
OTB plex HW transcode is working with best intel driver

## Current Behavior
Degraded or KO HW transcode.
Solve using command 
`docker exec -t PlexMediaServer rm “/usr/lib/plexmediaserver/lib/dri/iHD_drv_video.so”`
to have a working transcode with degraded capabilities (using i965 dri)

## Steps to Reproduce
1. Running classic linux on a Gemini Lake CPU (OMV 5 with a j5005 for example)
2. Run LSIO plex docker image with below compose
3. Activate plex HW transcode
4. Watch using HW transcode, get artefacts or no transcode issue
5. Remove /usr/lib/plexmediaserver/lib/dri/iHD_drv_video.so into docker image
6. Get a working transcode with a not nice CPU usage (i965 acceleration).

## Environment
**OS:**     Debian GNU/Linux 10 - OMV 5 
**CPU architecture:** x86_64      
**How docker service was installed:**      
OMV 5 auto docker install (GUI)

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - VERSION=docker
#      - UMASK_SET=022 #optional
#      - PLEX_CLAIM= #optional
    volumes:
      - /srv/dev-disk-by-label-data/appdata/plex/config:/config
      - /srv/dev-disk-by-label-data/appdata/plex/transcode:/transcode
      - /srv/dev-disk-by-label-media/media:/media
      - /srv/dev-disk-by-label-data/appdata/letsencrypt/etc/letsencrypt:/le-ssl
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
```

## Docker logs
Nothing revelant
