### ISSUE TITLE
The latest Ubuntu base image for armhf return random values for date/time

### ISSUE THREAD

**Issue by infothrill** [linuxserver/docker-plex#250]
It seems that all recent builds will have errounous date/time information on arm, as per https://bugs.launchpad.net/cloud-images/+bug/1896443

In the case of plex, this leads to partial degradation of the service, like the ability to scan libraries.

## Expected Behavior
container has correct date and time

## Current Behavior
random date and time, see https://bugs.launchpad.net/cloud-images/+bug/1896443

## Steps to Reproduce
run docker image newer than tag `arm32v7-version-1.20.5.3600-47c0d9038`

## Environment
**OS:** raspian buster
**CPU architecture:** arm32
**How docker service was installed:** `apt-get install docker-ce`

## Command used to create docker container (run/create/compose/screenshot)
`docker-compose up -d`

```
version: '2'
services:
    plex:
        container_name: plex
        dns:
        - 8.8.8.8
        - 8.8.4.4
        - 1.1.1.1
        environment:
            PGID: '1000'
            PUID: '1000'
            TZ: Europe/Berlin
            UMASK_SET: '022'
            VERSION: docker
        # image: linuxserver/plex:arm32v7-latest
        image: linuxserver/plex:arm32v7-version-1.20.5.3600-47c0d9038
        network_mode: host
        privileged: false
        restart: unless-stopped
        volumes:
        - /etc/localtime:/etc/localtime:ro
```
## Docker logs
irrelevant
