### ISSUE TITLE
armhf build problem : date is messed up, 100% CPU

### ISSUE THREAD

**Issue by Amaelh** [linuxserver/docker-plex#261]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hello, 

I use your image on a raspberry pi for some years now, and pull new versions from time to time. After my last pull plex suddenly started to use 100% CPU for days, and the logs displayed a random date between roughly 1927 and 1971. This seems to be a cross-compilation problem. 

Rolling back to linuxserver/plex:1.19.5.3112-b23ab3896-ls114 solves the problem.

I found a post on Internet about this same problem, indicating a cross-compilation problem on latest ubuntu focal, maybe this is your base image ? 

- [Reddit post](https://www.reddit.com/r/docker/comments/hdru82/time_in_docker_container_returns_random_value/)
- [launchpad bug](https://bugs.launchpad.net/cloud-images/+bug/1896443?comments=all)

Best regards,

------------------------------

## Expected Behavior
When starting the docker container, logs should display with current date/time :
`Feb 03, 2021 16:24:38.357 [0xb17fe440] DEBUG - Completed: [127.0.0.1:40718] 200 GET /channels/all (2 live) GZIP 1ms 387 bytes`

## Current Behavior
Timestamps are messed up and look like random : 
`Mar 14, 1929 16:09:28.-1261346 [0xaaffb430] DEBUG - HTTP simulating 408 after curl timeout`

## Steps to Reproduce
1. Use the following statement in docker-compose : 
`  image: linuxserver/plex:1.19.5.3112-b23ab3896-ls114`
2. Run the container
3. Look at logs in /config/Library/Application Support/Plex Media Server/Logs/Plex Media\ Server.log
4. Look at CPU : 100% for days

## Environment
**OS: ** Raspbian GNU/Linux 10 (buster)
**CPU architecture:** armhf (armv7l)
**How docker service was installed:** with apt-get from the official docker repo : https://download.docker.com/linux/raspbian buster stable

## Command used to create docker container (run/create/compose/screenshot)
docker-compose up -d with the following docker-compose.yml :
```
version: "2.2"

services:

  plex:
    image: linuxserver/plex
    network_mode: host
    restart: always
    ports:
      - 32400:32400
    environment:
      VERSION: docker
      PUID: 1000
      PGID: 1000
    volumes:
      - ~/data/plex/config:/config
      - ~/data/plex/transcode:/transcode
      - ~/data/videos/tvshows:/data/tvshows
      - ~/workspace/Sub-Zero.bundle:/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /dev/random:/dev/random:ro
      - /dev/urandom:/dev/urandom:ro
    cpu_percent: 75
    cpu_count: 3
```

## Docker logs
```
Jul 01, 1971 16:44:24.-1261346 [0xaaffb430] ERROR - Error issuing curl_easy_perform(handle): 28
Mar 14, 1929 16:09:28.-1261346 [0xaaffb430] DEBUG - HTTP simulating 408 after curl timeout
Jan 01, 1970 01:00:45.-1261346 [0xaaffb430] DEBUG - [com.plexapp.system] HTTP reply status 408, with 0 bytes of content.
Jul 01, 1971 16:44:24.-1261346 [0xb2bfe430] ERROR - Error issuing curl_easy_perform(handle): 28
Jan 01, 1970 01:00:00.-1261346 [0xb2bfe430] DEBUG - HTTP simulating 408 after curl timeout
Jan 01, 1970 01:00:45.-1261346 [0xb2bfe430] ERROR - Error parsing content.
Aug 08, 1928 06:14:24.-1261346 [0xb2bfe430] ERROR - Error parsing XML: Error parsing file.
Dec 06, 1928 10:00:36.-1261346 [0xb2bfe430] DEBUG - Media Server: Tested all servers in 1296050206.7 seconds.
Sep 26, 1927 14:28:32.-1261346 [0xb07ff430] DEBUG - MyPlex: Updating device connections (from timer: 1)
```
