### ISSUE TITLE
Can't read library

### ISSUE THREAD

**Issue by arielylim** [linuxserver/docker-plex#268]
I installed plex on my Raspberry Pi. It's working fine except that plex can't seem to find my media. Here's my `docker-compose.yml` file:

```
version: "3"
services:
  plex:
    image: linuxserver/plex:latest
    restart: unless-stopped
    container_name: plex
    hostname: RPi4
    network_mode: host
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ= 'America/Los_Angeles'
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - /Shared/media/movies:/movies
      - /Shared/media/tv-series:/tv
```
The `Shared` folder is something I setup in Samba. 

I believe I'm adding the library properly. For example, this is for the Movies. 
![plex](https://user-images.githubusercontent.com/60095540/116027515-f4635880-a609-11eb-9b60-ac636ce43f2b.png)

Same setup for TV Series. I added some .mkv files on both folders and plex can't seem to find them. I can open and watch the files in VLC in the same folder so i know they are working. Just not in plex. 

Any help would be appreciated. Thanks!
