### ISSUE TITLE
Unable to start Plex, Cirtical: libusb_init failed

### ISSUE THREAD

**Issue by bradcornford** [linuxserver/docker-plex#272]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Unable to start Plex, Cirtical: libusb_init failed

------------------------------

## Expected Behavior
Plex should start

## Current Behavior
Plex doesn't start

## Steps to Reproduce

1. docker-compose up -d plex

## Environment
**OS:** Centos 8
**CPU architecture:** x86_64
**How docker service was installed:**
Official docker repo

## Command used to create docker container (run/create/compose/screenshot)

```
...
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    networks:
      - docker
    security_opt:
      - no-new-privileges:true
    runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - VERSION=latest
      - UMASK=022
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./config/plex:/config
      - /mnt/hdd1:/transcode
      - /mnt/hdd2:/dvr
      - /mnt/unraid/movies:/movies
      - /mnt/unraid/series:/series
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
```

## Docker logs

```
plex         | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
plex         | [s6-init] ensuring user provided files have correct perms...exited 0.
plex         | [fix-attrs.d] applying ownership & permissions fixes...
plex         | [fix-attrs.d] done.
plex         | [cont-init.d] executing container initialization scripts...
plex         | [cont-init.d] 01-envfile: executing... 
plex         | [cont-init.d] 01-envfile: exited 0.
plex         | [cont-init.d] 10-adduser: executing... 
plex         | usermod: no changes
plex         | 
plex         | -------------------------------------
plex         |           _         ()
plex         |          | |  ___   _    __
plex         |          | | / __| | |  /  \
plex         |          | | \__ \ | | | () |
plex         |          |_| |___/ |_|  \__/
plex         | 
plex         | 
plex         | Brought to you by linuxserver.io
plex         | -------------------------------------
plex         | 
plex         | To support LSIO projects visit:
plex         | https://www.linuxserver.io/donate/
plex         | -------------------------------------
plex         | GID/UID
plex         | -------------------------------------
plex         | 
plex         | User uid:    1000
plex         | User gid:    1000
plex         | -------------------------------------
plex         | 
plex         | [cont-init.d] 10-adduser: exited 0.
plex         | [cont-init.d] 40-chown-files: executing... 
plex         | [cont-init.d] 40-chown-files: exited 0.
plex         | [cont-init.d] 45-plex-claim: executing... 
plex         | [cont-init.d] 45-plex-claim: exited 0.
plex         | [cont-init.d] 50-gid-video: executing... 
plex         | [cont-init.d] 50-gid-video: exited 0.
plex         | [cont-init.d] 60-plex-update: executing... 
plex         | 
plex         | 
plex         | 
plex         | #####################################################
plex         | #   Login via the webui at http://<ip>:32400/web    #
plex         | #   and restart the docker, because there was no    #
plex         | #      plex token found in the preference file      #
plex         | #####################################################
plex         | 
plex         | 
plex         | [cont-init.d] 60-plex-update: exited 0.
plex         | [cont-init.d] 99-custom-scripts: executing... 
plex         | [custom-init] no custom files found exiting...
plex         | [cont-init.d] 99-custom-scripts: exited 0.
plex         | [cont-init.d] done.
plex         | [services.d] starting services
plex         | [services.d] done.
plex         | Starting Plex Media Server.
plex         | Critical: libusb_init failed

```
