### ISSUE TITLE
Videos do not stream from local web interface (maybe related to 'Exec of EasyAudioEncoder failed')

### ISSUE THREAD

**Issue by garret** [linuxserver/docker-plex#273]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
On the web interface I should be able to play any movie/series as well as when using the Plex app on my Samsung TV.

## Current Behavior
When I am connected to the web interface with my browser and start playing any movie/series, there is a loading phase that never ends. Thus, the video is not played. 

![image](https://user-images.githubusercontent.com/27555/121304930-454eb800-c8fd-11eb-99de-7c5a04c6617a.png)

The same videos play without any issue when I use the Samsung TV Plex app connected to my Plex instance.  As you will see from the docker logs posted below, there is this line that sometimes appears when trying to stream a video: 

```
Jobs: Exec of /config/Library/Application Support/Plex Media Server/Codecs/EasyAudioEncoder-1431-linux-armv7neon/EasyAudioEncoder/EasyAudioEncoder failed. (13),
```

I don't know if it is related to my issue but looking on the internet I have seen that people have tried to remove the `Codecs` folder and restart the container. When doing that, the `Codecs` folder is re-downloaded by Plex but the line still seem to persist (and the issue is still there). 

## Steps to Reproduce
1. Connect to the PLEX web interface (inside my LAN).
2. Click to play any video.
3. Video never plays but a loading screen is presented which does not stop. 

## Environment
**OS:** Debian for Raspberry Pi (32 bit)
**CPU architecture:** arm (Raspberry Pi 4B, 4GB)
**How docker service was installed:**
From the docker repo through docker-compose. The PUID and PGID are for my local user (and not root).

## Command used to create docker container (run/create/compose/screenshot)
```
version: '3'
services:
    plex:
        container_name: plex
        network_mode: host
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - VERSION=docker
        volumes:
            - ${CONFIG_FOLDER}/plex:/config
            - ${LIBRARY_FOLDER}/series:/tv
            - ${LIBRARY_FOLDER}/movies:/movies
            - ${LIBRARY_FOLDER}/music:/music
        restart: unless-stopped
        image: ghcr.io/linuxserver/plex
```

## Docker logs
```
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1001,
User gid:    1001,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 40-chown-files: executing... ,
[cont-init.d] 40-chown-files: exited 0.,
[cont-init.d] 45-plex-claim: executing... ,
[cont-init.d] 45-plex-claim: exited 0.,
[cont-init.d] 50-gid-video: executing... ,
[cont-init.d] 50-gid-video: exited 0.,
[cont-init.d] 60-plex-update: executing... ,
Docker is used for versioning skip update check,
[cont-init.d] 60-plex-update: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Starting Plex Media Server.,
Critical: libusb_init failed,
Jobs: Exec of /config/Library/Application Support/Plex Media Server/Codecs/EasyAudioEncoder-1431-linux-armv7neon/EasyAudioEncoder/EasyAudioEncoder failed. (13),
```
