### ISSUE TITLE
Unable to delete files from Plex WebUI

### ISSUE THREAD

**Issue by isaacrlevin** [linuxserver/docker-plex#284]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Deleting file action should delete file

## Current Behavior
Get error message when trying to delete file

![image](https://user-images.githubusercontent.com/8878502/133690988-17a20316-1dd1-4200-b6dd-89c6e008c973.png)

## Steps to Reproduce

1. Go through delete file process
2. Get Error

## Environment
**OS:** Docker running in Ubuntu
**CPU architecture:** x86_64
**How docker service was installed:**

docker-compose

## Command used to create docker container (run/create/compose/screenshot)
ran below compose file with `docker-compose -f plex.yml up -d`

```yml
version: "3.7"
services:

## Plex Media Server
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: always
    privileged: true
    networks:
      traefik_proxy:
        ipv4_address: 192.168.50.200
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "33400:33400"
      - "33400:33400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "1900:1900/udp"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIGFOLDER/plex:/config
      - $STORAGEFOLDER/Movies:/MOVIES:ro
      - $STORAGEFOLDER/TV:/TV:ro
      - $STORAGEFOLDER/MUSIC:/MUSIC:ro
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/resolv.conf:/etc/resolv.conf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - VERSION=docker
      - PLEX_CLAIM=removed
networks:
  traefik_proxy:
    external: true

```

## Docker logs

```txt

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 45-plex-claim: executing... 
[cont-init.d] 45-plex-claim: exited 0.
[cont-init.d] 50-gid-video: executing... 
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing... 
Docker is used for versioning skip update check
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
```

My media is on a USB mounted HDD, with below fstab

```
/dev/disk/by-id/usb-Seagate_Backup+_Hub_BK_NA9RBXDY-0:0-part1 /mnt/data auto nosuid,nodev,nofail,x-gvfs-show,x-gvfs-name=data 0 0
````

## Permissions at host level

**`ls -l` output**

```
-rw-rw-rw-+ 1 isaac isaac      17786 Jan 24  2021
```

**`id isaac` output**

```
uid=1000(isaac) gid=1000(isaac) groups=1000(isaac),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),132(lxd),133(sambashare),998(docker)
```

## Permissions inside container

**`ls -l` output**

```
-rw-rw-rw-+ 1 abc abc      17786 Jan 24  2021
```

**`id abc` output**

```
uid=1000(abc) gid=1000(abc) groups=1000(abc),44(video),100(users),109(videoZ0Np3zwL)
```

I assume that there is some disconnect between the user that the Plex UI is using vs the ownership inside the container. I have looked at a few threads on this and have not been able to easily resolve it. Any help would be greatly appreciated
