### ISSUE TITLE
Plex tone mapping for transcoding 4K HDR to 1080p does not use hardware transcode because drivers are missing in the container.

### ISSUE THREAD

**Issue by nickp85** [linuxserver/docker-plex#297]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Plex should use hardware transcoding

## Current Behavior
Plex uses software transcoding

## Steps to Reproduce

1. Hardware is Intel Core i9 9900K
2. Enable hardware transcoding using the /dev/dri parameter
3. Enable tone mapping in Plex
4. Play a 4K HDR and transcode it down to 1080p

## Environment
**OS:** Unraid V6.9/6.10
**CPU architecture:** x86_64
**How docker service was installed:**
From the Unraid App Store

## Command used to create docker container (run/create/compose/screenshot)
Not sure how to see this in Unraid. Using the default container setup

## Docker logs

Not sure how to get this using Unraid

There is a script I found on the support forums months ago which adds the missing driver to the container so I run it every morning after Unraid checks for docker updates so it'll fix Plex automatically. This has been broken for months. Can the correct driver be added to the container as part of the build?

Script:

```
#!/bin/bash
#description=This script updates Beignet Driver to support last Intel GPUs for Plex Container

docker exec plex bash -c "apt update && apt -y install cmake pkg-config python ocl-icd-dev libegl1-mesa-dev ocl-icd-opencl-dev libdrm-dev libxfixes-dev libxext-dev llvm-7-dev clang-7 libclang-7-dev libtinfo-dev libedit-dev zlib1g-dev build-essential git clinfo"
docker exec plex git clone --branch comet-lake https://github.com/rcombs/beignet.git
docker exec plex bash -c "mkdir /beignet/build/ && cd /beignet/build && cmake -DLLVM_INSTALL_DIR=/usr/lib/llvm-7/bin .. && make -j8 && make install"
docker exec plex rm -rf beignet
docker exec plex bash -c "apt -y remove cmake pkg-config python ocl-icd-dev libegl1-mesa-dev ocl-icd-opencl-dev libdrm-dev libxfixes-dev libxext-dev llvm-7-dev clang-7 libclang-7-dev libtinfo-dev libedit-dev zlib1g-dev build-essential git && apt -y autoremove"
docker restart plex
docker exec plex clinfo -l
```

**Comment by aptalca** [comment]
Looks like you're compiling the beignet opencl driver's from source. That driver in our image (iirc) comes with the Plex package and is maintained by Plex.

**Comment by aptalca** [comment]
I lied. We install beignet. However, according to this post, beignet is being deprecated and being replaced with intel opencl icd, which we install the latest version of:
https://bugs.launchpad.net/ubuntu/+source/beignet/+bug/1905340

**Comment by nickp85** [comment]
Whatever is being installed with the container unfortunately does not work with tone mapping for 4K HDR > 1080p hardware transcoding with an Intel 9900K using QuickSync. Is there a way to fix this in the container so I don't need this script anymore?

**Comment by aptalca** [comment]
I don't have the hw but if I get you a test build, are you willing to test and report?

**Comment by nickp85** [comment]
Absolutely, just let me know how to update to the test build

**Comment by FlipABit** [comment]
I've run into the same issue running the latest on ubuntu 20.04.3. Following the related thread in the Plex forums, I ran [these commands](https://forums.plex.tv/t/anyone-have-been-able-to-hw-transcode-on-an-intel-nuc-11-iris-xe/695381/416), suggested by several users, within the docker image:

```
wget https://github.com/intel/compute-runtime/releases/download/21.47.21710/intel-gmmlib_21.3.3_amd64.deb 
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.9389/intel-igc-core_1.0.9389_amd64.deb 
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.9389/intel-igc-opencl_1.0.9389_amd64.deb 
wget https://github.com/intel/compute-runtime/releases/download/21.47.21710/intel-opencl-icd_21.47.21710_amd64.deb 
wget https://github.com/intel/compute-runtime/releases/download/21.47.21710/intel-level-zero-gpu_1.2.21710_amd64.deb 
sudo dpkg -i *.deb
```

Hardware transcoding works after running this. Happy to test out a build as well.

**Comment by Ge082** [comment]
```
wget https://github.com/intel/compute-runtime/releases/download/21.50.21939/intel-gmmlib_22.0.0_amd64.deb
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.9441/intel-igc-core_1.0.9441_amd64.deb
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.9441/intel-igc-opencl_1.0.9441_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/21.50.21939/intel-opencl-icd_21.50.21939_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/21.50.21939/intel-level-zero-gpu_1.2.21939_amd64.deb
sudo dpkg -i *.deb
```

These are the very latest packages from 3 days ago

**Comment by aptalca** [comment]
The only thing I can think of is that, in the image, we are installing those before the plex deb, whereas you guys are installing them again after the plex deb. Perhaps plex deb overwrites something like clinfo which breaks it. Let me move them around and get you guys an image to test

**Comment by aptalca** [comment]
Can you guys test this image and let us know? `lsiodev/plex:amd64-1.25.2.5319-c43dc0277-pkg-c2e7263a-dev-b00e11ed4a8c55eb3ff323752b0e5cb3ab1cbc9e`

Just replace `lscr.io/linuxserver/plex` in your docker run or compose yaml with the above and recreate

**Comment by nickp85** [comment]
How would I do this in Unraid?

**Comment by aptalca** [comment]
Edit the container and change the `Repositoy:` field

**Comment by nickp85** [comment]
Nope, software transcode after the update

**Comment by FlipABit** [comment]
Can also confirm that dev image still causes software tone mapping. It seems like maybe it's related to the specific versions of the intel packages being installed. Installing the ones I listed [here](https://github.com/linuxserver/docker-plex/issues/297#issuecomment-1000078053) causes hardware tone mapping to work correctly. Installing latest ones listed [here](https://github.com/linuxserver/docker-plex/issues/297#issuecomment-1000397739) results in software tone mapping.

**Comment by aptalca** [comment]
If that's the case, I'm afraid I won't have a fix for you. That would mean a regression/issue with the upstream drivers and should be fixed upstream. Pinning them to specific versions in our image would be a poor band-aid.

**Comment by SushiFu** [comment]
Hey guys,

I was actually debugging this issue on my own when I bumped into this issue, I'm running `linuxserver/plex:latest` image also in UnRaid 6.9.2 using docker-compose, CPU is Intel Rocket Lake.

What I found:
- When I installed [those versions](https://github.com/linuxserver/docker-plex/issues/297#issuecomment-1000078053) of ICR I got 4k to 1080p HW transcoding to work with tone mapping enabled, the latest `linuxserver/plex` image is already containing the latest version of ICR so it's causing a downgrade

- With the [latest version](https://github.com/linuxserver/docker-plex/issues/297#issuecomment-1000397739) of ICR, transcoding w/ tone mapping is made through SW

- I also noticed than completely removing the `beignet-opencl-icd` package + dependencies does not impact HW transcoding it's still working, but on the good side I don't see the `beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware` logs anymore when I tried to HW transcode w/ tone mapping enabled

**Comment by aptalca** [comment]
I just realized something. Do you guys use `VERSION=latest`? If so, it is likely installing the plex deb during init, so it would undo my change in the image. Can you try the dev image I posted above with `VERSION=docker`?
Thanks

**Comment by FlipABit** [comment]
> If that's the case, I'm afraid I won't have a fix for you. That would mean a regression/issue with the upstream drivers and should be fixed upstream. Pinning them to specific versions in our image would be a poor band-aid.

Indeed, I wouldn't expect that to be a good solution. It's definitely the latest version of the driver that causes the issue (21.50.21939). It works fine up through `21.49.21786`

**Comment by Ge082** [comment]
Tiger lake seems to have an issue pulling the latest image, it was working before.
Setting version=docker doesn't help eigher

**Comment by Ge082** [comment]
Downgrading drivers to https://github.com/intel/compute-runtime/releases/tag/21.49.21786 fixed it

**Comment by aptalca** [comment]
I need more specific info. I'm trying to test the order of installing things.

**Comment by FlipABit** [comment]
> I need more specific info. I'm trying to test the order of installing things.

I don't think it's the order of installing things that's the problem though, right? Even manually installing the latest drivers breaks tone mapping so it seems like we need an upstream fix for this as you mentioned earlier.

**Comment by aptalca** [comment]
I'll take you guys' word for it as I don't have concrete enough info to make that determination. But if you're sure that installing latest breaks but installing older works, then you should open an issue with the intel repo and let them know

**Comment by FlipABit** [comment]
Just for clarity / more info, here is my docker-compose file:

```
plex:
  image: lsiodev/plex:amd64-1.25.2.5319-c43dc0277-pkg-c2e7263a-dev-b00e11ed4a8c55eb3ff323752b0e5cb3ab1cbc9e
  container_name: "linuxserver-plex"
  volumes:
    - "/docker/plex:/config:rw"
    - "/docker/plex/transcode:/transcode:rw"
    - "/mnt/user/data/media/mounts/918/media/Video/Movies:/media/movies/hd/01:rw"
  environment:
    - PLEX_CLAIM=<redacted>
    - VERSION=docker
    - PGID=1000
    - PUID=1000
    - PLEX_UID=1000
    - PLEX_GID=1000
    - TZ=America/Los_Angeles
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - HOME=/root/media
    - LANGUAGE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - TERM=xterm
    - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    - DEBIAN_FRONTEND=noninteractive
    - PLEX_DOWNLOAD=https://downloads.plex.tv/plex-media-server-new
    - PLEX_ARCH=amd64
    - PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/config/Library/Application Support
    - PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver
    - PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
    - PLEX_MEDIA_SERVER_USER=mistame
    - PLEX_MEDIA_SERVER_INFO_VENDOR=docker
    - PLEX_MEDIA_SERVER_INFO_DEVICE=Docker Container (LinuxServer.io)
    - ADVERTISE_IP="http://192.168.1.167:32400/"
    - VERSON=latest
  devices:
    - "/dev/dri/card0:/dev/dri/card0"
    - "/dev/dri/renderD128:/dev/dri/renderD128"
  privileged: false
  net: "host"
  restart: always
```

To get tone mapping working:
```
docker exec -it <image id> /bin/bash

> wget https://github.com/intel/compute-runtime/releases/download/21.49.21786/intel-gmmlib_21.3.3_amd64.deb
> wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.9441/intel-igc-core_1.0.9441_amd64.deb
> wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.9441/intel-igc-opencl_1.0.9441_amd64.deb
> wget https://github.com/intel/compute-runtime/releases/download/21.49.21786/intel-opencl-icd_21.49.21786_amd64.deb
> wget https://github.com/intel/compute-runtime/releases/download/21.49.21786/intel-level-zero-gpu_1.2.21786_amd64.deb
> dpkg -i *.deb
```
