### ISSUE TITLE
Unable to run initial setup without host network type

### ISSUE THREAD

**Issue by hneiva** [linuxserver/docker-plex#301]
------------------------------

## Expected Behavior
I should be able to initialize a fresh server with ports listed (bridge mode)

## Current Behavior
When I start a server with ports listed (`bridge` network type), everything looks normal, but initial setup page does not load

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/3451557/150915111-4d450ca9-f967-4eec-a215-800e23987def.png">

## Steps to Reproduce
I'm using an OrangePi 3 with Armbian (fresh install)
1. docker compose:
```
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "1900:1900/udp"
      - "3005:3005/tcp"
      - "5353:5353/udp"
      - "8324:8324/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469/tcp"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - DOCKER_MODS=linuxserver/mods:plex-absolute-hama
    volumes:
      - /opt/plex/config:/config
      - /data/series:/tv
      - /data/movies:/movies
    restart: unless-stopped
```
2. run `docker-compose up -d plex`
3. open browser on port 32400
4. Plex page shows up, instead of initial setup.
5. Re-add `bridge` networking instead of `host` with ports and recycle container, everything works fine 

## Environment
Armbian 21.08.6 Buster
OrangePi [arm64]

If someone can verify this is the case, I'd suggest adding a note in README.md until a fix can be put in place.
