### ISSUE TITLE
Recreating container makes it dead sometimes

### ISSUE THREAD

**Issue by Maypul** [linuxserver/docker-plex#302]
------------------------------

## Expected Behavior
Docker compose up -> remove old container, start up new one updated

## Current Behavior
Docker compose up -> somestimes new container gets created and old one gets stuck in deletion process. Nothing I have done would unhung it, once I let it be for hours. Only solution for me is to turn of docker and manually remove directory from docker, start up docker and create new container.

## Steps to Reproduce
1. Pull new image
2. Docker compose up
3. See new container created, old one getting stuck

ERROR: for Plex  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for plex  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

But that's only logging because it is taking long and default value is 60. If I rebuild with other containers that takes some time, they finish successfully despite this error.

## Environment
**OS: DSM 7, Synology
**CPU architecture:** arm64, AMD Ryzen V1500B
**How docker service was installed:**
NAS OS provided. Nothing changed, modified from default OS.

## Command used to create docker container (run/create/compose/screenshot)
sudo docker-compose -p 'XXX' -f /volume1/Docker/Docker-Compose.yml up -d

Revelant plex config:
```
  plex:
    container_name: Plex
    hostname: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    privileged: false
    networks:
      Proxy:
    ports:
      - 32400:32400/tcp
    security_opt:
      - no-new-privileges:true
    volumes:
      - $SHR_DOCKER/Plex:/config:rw
      - $SHR_MOVIES:/media/Movies:ro
      - $SHR_SHORTS:/media/Shorts:ro
      - $SHR_SERIES:/media/Series:ro
    environment:
      - PUID=$PUID_DOCKERUSER
      - PGID=$PGID_DOCKERGROUP
      - VERSION=docker
      - FILE__PLEX_CLAIM=/run/secrets/plex_claim
    secrets:
      - plex_claim
```

Other than than, Plex is vanilla, nothing changed inside, just left running.

## Docker logs

No logs, Container dead visible in Portainer:
http://prntscr.com/26opb1j (will change status if I shut down docker and run it on without deleting it, otherwise it will say deletion is in progress)

It happens only to this container, I run about 20 other and few more from linuxserver. Happened few times on different versions, unsure what causes it. App alone seems to be working fine. Sometimes rebuildings works, but that's rare. Last 4 times it got stuck though.

Only thing that could be said is unusual for this NAS at the moment is that it's rebuilding RAID, but 2 mb/s and everything else runs smoothly, I doubt that is the issue. That also means I currently cannot reboot to see if it would solve the issue, but before (as it is happening for me for quite some time, the nas had reboots and it still happened).

Edit: Oh, right, possible workaround is to disable the container in UI and delete it manually then compose up. I would need to verify it if I rebuild it again, as I cannot keep docker down for manual removal often but I seem to recall this way worked more often.
