### ISSUE TITLE
Critical: libusb_init failed | DVB

### ISSUE THREAD

**Issue by StephanGR** [linuxserver/docker-plex#303]
Hello,

I recently bought new HAUPPAUGE DualHD tuner for plex DVR

But when I go to DVR Settings in plex I got this error in logs of container : Critical: libusb_init failed

This is my compose file : 

```yaml
version: "3.8"

services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Paris
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    volumes:
      - /srv/dev-disk-by-uuid-04a5a2af-6693-4906-a18f-ffd8942570c1/DATA/Plex-Apps/plex/config:/config
      - /srv/dev-disk-by-uuid-04a5a2af-6693-4906-a18f-ffd8942570c1/DATA/SERIES:/tv
      - /srv/dev-disk-by-uuid-04a5a2af-6693-4906-a18f-ffd8942570c1/DATA/FILMS:/movies
    restart: unless-stopped
```

Anyone have an idea about this problem? 

Thanks in advance

PS : my folder /dev/dvb is chown of properties `1000:1000`
