### ISSUE TITLE
Hardware transcoding not working on QNAP device

### ISSUE THREAD

**Issue by jamesking420** [linuxserver/docker-plex#305]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Hardware transcoding should be available on a QNAP TS653-D when a plexpass user is running the docker container.

## Current Behavior
hardware transcoding does not work.

## Steps to Reproduce

1.  Run docker container with details as follows.  Plex will not be able to access hardware transcoding.
2.  I appreciate it looks like it should be working under these circumstances but what I actually see is included in some plex logs below.
3.  Hardware transcoding works with chmod 666 /dev/dri* in an autorun boot script or added to the docker scripts.
4.

## Environment
**OS:**  QNAP QTS 5.0.0.1932
**CPU architecture:** x86_64

**How docker service was installed:**
Containerstation from QNAP

## Command used to create docker container (run/create/compose/screenshot)

docker-compose.yaml:
```
version: "3.8"

services:

  plexdocker:
    image: lscr.io/linuxserver/plex:latest
    container_name: Plex-Compose
    environment:
      - VERSION=latest
    volumes:
      - ${DockerPath}/Plex/Config:/config
      - ${MultimediaPath}/TV:/tv
      - ${MultimediaPath}/Movies:/movies
      - "${MultimediaPath}/Home Movies:/home movies"
      - "${MultimediaPath}/Important Documents/Plex Backups:/backups"
      - "${MultimediaPath}/Security:/security"
    network_mode: host
    devices:
      - /dev/dri:/dev/dri  
    restart: unless-stopped
```
environment.env:
```
PUID=1001
PGID=0
TZ=Europe/London
UMASK_SET=022
```

.env:
```
MultimediaPath=/share/Multimedia
DockerPath=/share/DockerCompose
COMPOSE_PROJECT_NAME=MediaStack
```

## Docker logs

```
-----
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 45-plex-claim: executing... 
[cont-init.d] 45-plex-claim: exited 0.
[cont-init.d] 50-gid-video: executing... 
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing... 
No update required
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Plex Media Server.
Critical: libusb_init failed
Dolby, Dolby Digital, Dolby Digital Plus, Dolby TrueHD and the double D symbol are trademarks of Dolby Laboratories.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
```

**Comment by jamesking420** [comment]
Sample Plex Log - more can be provided if I know what to provide! :-)
```
Mar 04, 2022 11:33:13.049 [0x7f7c50f5cb38] DEBUG - [Transcode] Codecs: testing h264_vaapi (encoder)
Mar 04, 2022 11:33:13.049 [0x7f7c50f5cb38] DEBUG - [Transcode] Codecs: hardware transcoding: testing API vaapi
Mar 04, 2022 11:33:13.049 [0x7f7c50f5cb38] DEBUG - [Transcode] Codecs: hardware transcoding: opening hw device failed - probably not supported by this system, error: Generic error in an external library
Mar 04, 2022 11:33:13.049 [0x7f7c50f5cb38] DEBUG - [Transcode] Could not create hardware context for h264_vaapi
Mar 04, 2022 11:33:13.049 [0x7f7c50f5cb38] DEBUG - [Transcode] Codecs: testing h264_nvenc (encoder)
Mar 04, 2022 11:33:13.049 [0x7f7c50f5cb38] DEBUG - [Transcode] Codecs: hardware transcoding: testing API nvenc
Mar 04, 2022 11:33:13.049 [0x7f7c50f5cb38] ERROR - [Transcode] [FFMPEG] - Cannot load libcuda.so.1
Mar 04, 2022 11:33:13.049 [0x7f7c50f5cb38] ERROR - [Transcode] [FFMPEG] - Could not dynamically load CUDA
Mar 04, 2022 11:33:13.049 [0x7f7c50f5cb38] DEBUG - [Transcode] Codecs: hardware transcoding: opening hw device failed - probably not supported by this system, error: Unknown error occurred
Mar 04, 2022 11:33:13.049 [0x7f7c50f5cb38] DEBUG - [Transcode] Could not create hardware context for h264_nvenc
Mar 04, 2022 11:33:13.049 [0x7f7c50f5cb38] DEBUG - [Transcode] Codecs: testing hevc (decoder) with hwdevice vaapi
Mar 04, 2022 11:33:13.050 [0x7f7c50f5cb38] DEBUG - [Transcode] Codecs: hardware transcoding: testing API vaapi
Mar 04, 2022 11:33:13.050 [0x7f7c50f5cb38] DEBUG - [Transcode] Codecs: hardware transcoding: opening hw device failed - probably not supported by this system, error: Generic error in an external library
Mar 04, 2022 11:33:13.050 [0x7f7c50f5cb38] DEBUG - [Transcode] Could not create hardware context for hevc
Mar 04, 2022 11:33:13.050 [0x7f7c50f5cb38] DEBUG - [Transcode] Codecs: testing hevc (decoder) with hwdevice nvdec
Mar 04, 2022 11:33:13.050 [0x7f7c50f5cb38] DEBUG - [Transcode] Codecs: hardware transcoding: testing API nvdec
```

```/dev/dri``` permissions:
```
crw-------  1 admin administrators 226,   0 2022-03-01 16:42 card0
crw-------  1 admin administrators 226, 128 2022-03-01 16:42 renderD128
```

Note that the PUID for the docker container is not admin, but is in the administrators group.  I did try changing it to admin to see if it helped, but it did not seem to.

**Comment by aptalca** [comment]
The provided docker arguments don't match the container log. According to the container log, no PUID/PGID is set so it's running as the default 911:911.

Perhaps the device mapping is also not correct in the container.

**Comment by jamesking420** [comment]
Thank you for that @aptalca 
I have now added ```env_file: environment.env``` to the docker-compose file as follows, which gives a new log which I also include.  However, I think that /dev/dri is mapped correctly because

- It's as documented
- a check of ```ls -lh /dev/dri``` from an ssh to my host shows the relevant files
- when the permissions are changed on that location with ```chmod 666 /dev/dri/*``` (or the script referenced above is used) and the container restarted, the hardware transcoding starts working.

```
version: "3.8"

services:
  plexdocker:
    image: lscr.io/linuxserver/plex:latest
    env_file: environment.env
    container_name: Plex-Compose
    environment:
      - VERSION=latest
    volumes:
      - ${DockerPath}/Plex/Config:/config
      - ${MultimediaPath}/TV:/tv
      - ${MultimediaPath}/Movies:/movies
      - "${MultimediaPath}/Home Movies:/home movies"
      - "${MultimediaPath}/Important Documents/Plex Backups:/backups"
      - "${MultimediaPath}/Security:/security"
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
```

The new log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1001
User gid:    0
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 45-plex-claim: executing... 
[cont-init.d] 45-plex-claim: exited 0.
[cont-init.d] 50-gid-video: executing... 
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing... 
No update required
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
Critical: libusb_init failed
Dolby, Dolby Digital, Dolby Digital Plus, Dolby TrueHD and the double D symbol are trademarks of Dolby Laboratories.

```
