### ISSUE TITLE
Provide AllowedNetworks and FriendlyName through environment settings

### ISSUE THREAD

**Issue by yvbeek** [linuxserver/docker-plex#324]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
It would be very useful to be able to pass the following arguments for the first run:

- `PLEX_SERVER_NAME`
  - controls the `FriendlyName` setting in the `Preferences.xml` file, making it easier to recognize this server
  - sets the `X-Plex-Device-Name` header when the server is claimed, making sure the correct name shows up in Authorized Devices underneath your Plex Account, and prevents confusion when you have multiple servers

- `PLEX_ALLOWED_NETWORKS`
  - controls the `allowedNetworks` setting in the `Preferences.xml` file, making it easier to reach the server when it is in a different subnet or vlan. Otherwise it can be difficult to run setup.

Example:

```
---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim_abcdefghijkl
      - PLEX_SERVER_NAME=Atlas
      - PLEX_ALLOWED_NETWORKS=192.168.10.0/24
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies
    restart: unless-stopped
```

## Current Behavior
In `/etc/cont-init.d/45-plex-claim` the server name is hardcoded to `PlexMediaServer`. It would be great if we could use the `PLEX_SERVER_NAME` environment variable here. And then also write the server name as `FriendlyName` in `Preferences.xml`

There currently is no easy way to get it under a different name.

## Alternatives Considered
For the server name I don't see an alternative. It is hard to edit `45-plex-claim`.

To set the `allowedNetworks`, you would currently have to run the docker at least once. Then go into the `Preferences.xml` file and add `allowedNetworks` manually. This can be error prone and could make setup more complex.
