### ISSUE TITLE
Bad documentation? NVENC unavailable without NVIDIA_DRIVER_CAPABILITIES=all

### ISSUE THREAD

**Issue by pannal** [linuxserver/docker-plex#340]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The documentation states that for enabling hw acceleration only the nvidia docker runtime and the `NVIDIA_VISIBLE_DEVICES=all` environment variable is necessary.

This isn't true for my case. This results in:
```
Oct 21, 2022 16:01:12.613 [0x7f1c07a08b38] ERROR - [Req#225/Transcode] [FFMPEG] - Cannot load libnvidia-encode.so.1
Oct 21, 2022 16:01:12.613 [0x7f1c07a08b38] ERROR - [Req#225/Transcode] [FFMPEG] - The minimum required Nvidia driver for nvenc is 418.30 or newer
Oct 21, 2022 16:01:12.613 [0x7f1c07a08b38] VERBOSE - [Req#225/Transcode] [FFMPEG] - Nvenc unloaded
```

Only once I set the environment variable `NVIDIA_DRIVER_CAPABILITIES=all` as well, hw accell works.

------------------------------

## Expected Behavior
As per the documentation, `NVIDIA_DRIVER_CAPABILITIES=all` shouldn't be necessary.

## Current Behavior
Without `NVIDIA_DRIVER_CAPABILITIES=all` hw accel doesn't work.

## Steps to Reproduce
Install lsio/docker-plex, try using NVENC.

## Environment
**OS:** Ubuntu 22.04.1 LTS
**CPU architecture:** x86_64
**How docker service was installed:** official repo

## Command used to create docker container (run/create/compose/screenshot)
```
plex:
    image: plexinc/pms-docker:beta
    container_name: plex
    runtime: nvidia
    restart: unless-stopped
    depends_on:
      - wgair
    network_mode: "service:wgair"

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PLEX_UID=1001
      - PLEX_GID=1001
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
      - ALLOWED_NETWORKS=127.0.0.1,192.168.0.2,192.168.0.5,192.168.0.6,192.168.0.8
      - TZ=Europe/Berlin
      - PLEX_CLAIM=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    volumes:
      - /plexmeta:/config
      - /media/ram:/transcode
      - ...
    labels:
      - "autoheal=true"
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 40-plex-first-run: executing...
Plex Media Server first run setup complete
[cont-init.d] 40-plex-first-run: exited 0.
[cont-init.d] 45-plex-hw-transcode-and-connected-tuner: executing...
[cont-init.d] 45-plex-hw-transcode-and-connected-tuner: exited 0.
[cont-init.d] 50-plex-update: executing...
Attempting to upgrade to: 1.29.1.6316-f4cdfea9c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   190    0   190    0     0   1250      0 --:--:-- --:--:-- --:--:--  1250
100 81.0M  100 81.0M    0     0  41.0M      0  0:00:01  0:00:01 --:--:-- 53.8M
Selecting previously unselected package plexmediaserver.
(Reading database ... 7274 files and directories currently installed.)
Preparing to unpack /tmp/plexmediaserver.deb ...
PlexMediaServer install: Pre-installation Validation.
PlexMediaServer install: Custom environment detected.  Skipping preinstallation validation.
Unpacking plexmediaserver (1.29.1.6316-f4cdfea9c) ...
Setting up plexmediaserver (1.29.1.6316-f4cdfea9c) ...
PlexMediaServer install: Custom environment detected.  Skipping postinstallation tasks. Continuing.
[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
Critical: libusb_init failed
Dolby, Dolby Digital, Dolby Digital Plus, Dolby TrueHD and the double D symbol are trademarks of Dolby Laboratories.
```
