### ISSUE TITLE
[BUG] Docker Attempting to mkdir Existing Directory

### ISSUE THREAD

**Issue by AngelaDMerkel** [linuxserver/docker-plex#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I attempt to start a new docker container which binds to an rclone mount the container attempts to mkdir the existing directory. This should not be a permission issue as I run `rclone mount` with options that ought to provide proper permissions: `rclone mount --dir-perms 777 --file-perms 777 --uid 1000 --gid 1000 plex-mount:/ /mnt/usb/plex/plex-mount`

My docker-compose is:

```
---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=#claim
    volumes:
      - /mnt/usb/plex/config:/config
      - /mnt/usb/plex/plex-mount:/media:shared
      - /mnt/usb/plex/transcode:/transcode
    restart: unless-stopped
```

### Expected Behavior

The container should start and bind to the rclone mount so that plex can see my media. 

### Steps To Reproduce

Mount the the rclone volume with the described flags and then attempt to start a plex container using the docker-compose

### Environment

```markdown
piOS 11 with docker installed via official install script
```

### CPU architecture

arm64

### Docker creation

```bash
---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=#claim
    volumes:
      - /mnt/usb/plex/config:/config
      - /mnt/usb/plex/plex-mount:/media:shared
      - /mnt/usb/plex/transcode:/transcode
    restart: unless-stopped
```

### Container logs

```bash
Stack fails to deploy container, no logs.
```
