### ISSUE TITLE
[BUG] Hardware transcoding (Intel QS) stop working on 1.32.2

### ISSUE THREAD

**Issue by Jorman** [linuxserver/docker-plex#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I ask Plex to transcode one video, hw transcoding is not working anymore

### Steps To Reproduce

Till docker version 1.32.1 hw transcode was working, but with 1.32.2 hw stop working
```
[Req#11cd/Transcode] [FFMPEG] - Failed to initialise VAAPI connection: -1 (unknown libva error).
[Req#11cd/Transcode] Codecs: hardware transcoding: opening hw device failed - probably not supported by this system, error: I/O error
[Req#11cd/Transcode] Could not create hardware context for h264
```
Any idea why it stopped working?

J

### Environment

```markdown
- OS: Debian 11
- How docker service was installed: version 24.0.2, build cb74dfc
- CPU: Intel(R) Celeron(R) CPU J3355 @ 2.00GHz
- VAINFO on host:

libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
```
```


### CPU architecture

x86-64

### Docker creation

```bash
version: "3"
services:
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex-server
        network_mode: host
        environment:
            - PUID=65534
            - PGID=65534
            - TZ=Europe/Rome
            - VERSION=docker
        volumes:
            - /docker-config/AppData/Config/Plex:/config
            - /data/Multimedia/tv:/tv
            - /data/Multimedia/movies:/movies
            - /data/Multimedia/photo:/photo
        devices:
            - /dev/dri:/dev/dri
        restart: unless-stopped
```

### Container logs

```bash
docker logs plex-server   
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    65534
User GID:    65534
───────────────────────────────────────

**** Server already claimed ****
**** creating video group videod7u0 with id 107 ****
**** adding /dev/dri/renderD128 to video group videod7u0 with id 107 ****
**** adding /dev/dri/card0 to video group videod7u0 with id 107 ****
Docker is used for versioning skip update check
[custom-init] No custom files found, skipping...
Starting Plex Media Server. . . (you can ignore the libusb_init error)
[ls.io-init] done.
Critical: libusb_init failed
```
