### ISSUE TITLE
[FEAT] Note switch to nvidia-container-toolkit

### ISSUE THREAD

**Issue by Fyko** [linuxserver/docker-plex#381]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

As of https://github.com/NVIDIA/nvidia-docker/commit/69b790e22838dfb6b41de07a7ece3763dc5f97a3, https://github.com/NVIDIA/nvidia-docker is deprecated. Everyone should switch to https://github.com/NVIDIA/nvidia-container-toolkit.

### Reason for change

nvidia-docker deprecated

### Proposed code change

documentation (i can take on this feat)

**Comment by TopCheddar27** [comment]
I just wanted to add my experience here testing this change. In short, I do not believe that the necessary changes have been made to properly send ffmpeg requests to the new Nvidia-Container-Toolkit integration. You see the job make it to the GPU, and you even see some compute happen. However it crashes out after a second or two. Normally, you would see the ffmpeg flags within the command in NVTOP. None of them are seen in the second or two it does show in NVTOP. 

The kicker is, if you select "Convert Automatically", it does seem to do some consistent compute for playback. It did seem to be a drop in replacement for the previous nvidia-docker setup. It should use the same "nvidia" runtime as defined within the deamon.json.

Not sure what needs to be changed / tested, but am willing to test in my environment! Below is some specs.

Relevant Specs: Ubuntu 20.04 LTS - 1650 Super - NVIDIA Driver 470.223.02-0ubuntu0.20.04.1

**Comment by cohenchris** [comment]
I haven't dived very deep into this, but it seems that this issue has broken my instance. When creating the plex container, I see this error message:

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown
```

The relevant parts of my docker-compose file look like this:
```
deploy:                                                                                                                        
  resources:                                                                                                                     
    reservations:                                                                                                                  
      devices:                                                                                                                       
        - capabilities: [gpu]
environment:
 - PGID
 - PUID
 - TZ
 - DOCKER_MODS=gilbn/theme.park:plex # custom CSS 
 - PLEX_CLAIM=${PLEX_CLAIM}
 - NVIDIA_VISIBLE_DEVICES=all
 - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
```

I have changed nothing recently.
