### ISSUE TITLE
"Received packet from invalid interface" in logs

### ISSUE THREAD

**Issue by the3rdhbtaylor** [linuxserver/docker-plex#50]
When I look at the logs for my Plex container (via `docker logs -f plex`), I see many lines reading, "Received packet from invalid interface". Here is the portion of my docker-compose.yml associated with Plex:

```
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/storage:/data
    network_mode: host
    restart: always
    environment:
      - VERSION=latest
      - PUID=${PUID}
      - PGID=${PGID}
```

The PUID and PGID are defined as vars, and they correspond to the IDs for dockeruser and dockergroup.

I don't recall seeing this when I first got it running, but I see it all of the time now. Restarting the Plex container doesn't change the behavior, nor does restarting the entire host.
