### ISSUE TITLE
Conversion failed. The transcoder crashed or failed to start up. Its exit code was 1

### ISSUE THREAD

**Issue by AndreKlang** [linuxserver/docker-plex#95]
## Issue

When trying to start a video, it stalls for a while, then I get the error ```Conversion failed. The transcoder crashed or failed to start up. Its exit code was 1```

A few months ago when updating to version 1.something I ran in to this, and found out that plex had moved the transcode binarys to the library folder (/config in this image), but since docker volumes are mounted with noexec it can't be run from there. My solution back then was to stick with version 0.9.16.6.1993-5089475 (last one before the move). But now that is not an option any more since plex updated their /web/app.

**My question is**, how has everyone else solved this? Or is nobody using volume mounts for /config?

## My env
Host OS: Linux Mint
Log output: None (when error occures)
No symlinks in mounts

Using docker-compose to start container:
```yml
  plex:
    build: ./.plex/image/
    container_name: plex
    privileged: true
    network_mode: "host"
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: latest
      TZ: europe/stockholm
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - ./.plex:/config
    volumes_from:
      - data:ro
```
I'm running rar2fs on the same container, that's why I'm using a different image (that has ```FROM linuxserver/plex```)
